---
- hosts: all
  remote_user: slave
  become: yes
  
  tasks:
  - name: "Copy The Conatiner Files"
    copy:
     src: container_create.yml
     dest: /root/
     force: yes
  - name: "Copy The Service files"
    copy: 
     src: service_create.yml
     dest: /root/
     force: yes
