---
- hosts: all
  remote_user: slave
  become: yes
  
  tasks:
  - name: "Copy The Conatiner Files"
    copy:
     src: green.conf
     dest: /etc/nginx/conf.d
     force: yes
  - name: "Delet the Files"
    command: rm -rf /etc/nginx/conf.d/blue.conf
  - name: Enable service httpd, and not touch the state
    service:
      name: nginx
      state: restarted
    
